[cart] - fix cartServiceFailure flag
open-telemetry/opentelemetry-demo pull request #1313
Opened 2023-12-22 20:55 UTC by puckpuck

# Changes
Fixes: #1306 

Adds the environment variable to enable the cart to find the feature flag service. It also removes code from the cart service to do a random check 10% of the time. Now that the feature flag service supports this functionality, we should leverage it there instead. Set the feature flag to `0.1` to have it fail 10% of the time.

* [ ] `CHANGELOG.md` updated to document new feature additions

2023-12-27 22:33 UTC, julianocosta89 requested changes
I think we are still missing something here.

I've set the flag `cartServiceFailure` to `1.0` and I didn't get the errors on the CartService, but in the Frontend Proxy.

Here is the full Trace:

```json
{
    "data": [
        {
            "traceID": "864f33c21e7388fc27615dd9f45cb499",
            "spans": [
                {
                    "traceID": "864f33c21e7388fc27615dd9f45cb499",
                    "spanID": "9a241ef3bbcd3bec",
                    "operationName": "CurrencyService/Convert",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "864f33c21e7388fc27615dd9f45cb499",
                            "spanID": "dc1d62bcbafb1410"
                        }
                    ],
                    "startTime": 1703716193160551,
                    "duration": 117,
                    "tags": [
                        {
                            "key": "rpc.system",
                            "type": "string",
                            "value": "grpc"
                        },
                        {
                            "key": "rpc.service",
                            "type": "string",
                            "value": "CurrencyService"
                        },
                        {
                            "key": "rpc.method",
                            "type": "string",
                            "value": "Convert"
                        },
                        {
                            "key": "rpc.grpc.status_code",
                            "type": "int64",
                            "value": 0
                        },
                        {
                            "key": "app.currency.conversion.from",
                            "type": "string",
                            "value": "USD"
                        },
                        {
                            "key": "app.currency.conversion.to",
                            "type": "string",
                            "value": "BRL"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "server"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "OK"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "otlp"
                        }
                    ],
                    "logs": [
                        {
                            "timestamp": 1703716193160575,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "Processing currency conversion request"
                                }
                            ]
                        },
                        {
                            "timestamp": 1703716193160638,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "Conversion successful, response sent back"
                                }
                            ]
                        }
                    ],
                    "processID": "p1",
                    "warnings": null
                },
                {
                    "traceID": "864f33c21e7388fc27615dd9f45cb499",
                    "spanID": "a0708f9b87e22858",
                    "operationName": "CurrencyService/Convert",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "864f33c21e7388fc27615dd9f45cb499",
                            "spanID": "1e98c7af67d04cd0"
                        }
                    ],
                    "startTime": 1703716193179759,
                    "duration": 96,
                    "tags": [
                        {
                            "key": "rpc.system",
                            "type": "string",
                            "value": "grpc"
                        },
                        {
                            "key": "rpc.service",
                            "type": "string",
                            "value": "CurrencyService"
                        },
                        {
                            "key": "rpc.method",
                            "type": "string",
                            "value": "Convert"
                        },
                        {
                            "key": "rpc.grpc.status_code",
                            "type": "int64",
                            "value": 0
                        },
                        {
                            "key": "app.currency.conversion.from",
                            "type": "string",
                            "value": "USD"
                        },
                        {
                            "key": "app.currency.conversion.to",
                            "type": "string",
                            "value": "BRL"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "server"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "OK"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "otlp"
                        }
                    ],
                    "logs": [
                        {
                            "timestamp": 1703716193179777,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "Processing currency conversion request"
                                }
                            ]
                        },
                        {
                            "timestamp": 1703716193179831,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "Conversion successful, response sent back"
                                }
                            ]
                        }
                    ],
                    "processID": "p1",
                    "warnings": null
                },
                {
                    "traceID": "864f33c21e7388fc27615dd9f45cb499",
                    "spanID": "80164af40fe94231",
                    "operationName": "calculate-quote",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "864f33c21e7388fc27615dd9f45cb499",
                            "spanID": "3a37e0ccc3a05556"
                        }
                    ],
                    "startTime": 1703716193174014,
                    "duration": 22,
                    "tags": [
                        {
                            "key": "app.quote.items.count",
                            "type": "int64",
                            "value" [...]

2024-01-02 09:08 UTC, mviitane commented
@julianocosta89 for me this PR fixed the problem. I see the rejects from CartService/EmptyCart when enabling the feature flag with 1.0. I don't see any rejects in frontend-proxy.
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/74129181/24fc823c-acb9-4e6b-9da9-1ac067ad1c92)

2024-01-02 09:08 UTC, mviitane approved these changes

2024-01-02 09:11 UTC, julianocosta89 commented
@mviitane does that reflect on the trace as well?

2024-01-02 09:15 UTC, mviitane commented
> @mviitane does that reflect on the trace as well?

Yes
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/74129181/c7a6efcc-6933-4d2e-84ab-47c0669e6c89)

2024-01-02 12:34 UTC, julianocosta89 commented
I'll try a fresh build

2024-01-02 13:51 UTC, julianocosta89 approved these changes
Yep, thanks @mviitane!
It works as expected

2024-01-02 13:51 UTC, merged