Recommendation service e2e testing
open-telemetry/opentelemetry-demo pull request #198
Opened 2022-07-10 02:01 UTC by mic-max

Towards #195 

Merge after: #196 
(If anyone knows a good git workflow for creating a PR based off another one that hasn't yet been merged yet please let me know so I can make these PRs cleaner since this one include all the previous branches commits - all I did was `git checkout -b recc-service-test` while on the `mic-max:e2e-tests` branch` anyways... shoot me a dm 😄)

## Changes

- Delete the `client.py`, essentially a manual version of this test
- Open port to localhost so we can connect to the container from the test program

The 1 test sends 5 product ids. this makes sure that the recommendation service always sends back the same array 4 product ids (random ordering) - it caps at 5 recommendations and wont include anything you sent in the request. I was originally going to test it just by including 1 id in the request but then its possible the service sends back 5 products that dont include the one in my request just by chance. So this way is more robust, still not perfect though since the random generator isn't seeded and more reasons I won't get into.

2022-07-12 19:55 UTC, julianocosta89 requested changes
I've tried the test and they failed in 4 out 5 tests, was that intended?

```shell
✖ payment: valid credit card Rejected promise returned by test
✖ payment: invalid credit card 
✖ payment: amex credit card not allowed 
✖ payment: expired credit card 
✔ recommendation: list products
```

2022-07-25 19:11 UTC, mic-max commented on test/README.md
> +1. Start the services you want to test with `docker compose up <service>`
Ya if the service has changed it should be rebuilt. I can make it include the `--build` flag

2022-07-25 19:19 UTC, mic-max commented
> I've tried the test and they failed in 4 out 5 tests, was that intended?
> 
> ```shell
> ✖ payment: valid credit card Rejected promise returned by test
> ✖ payment: invalid credit card 
> ✖ payment: amex credit card not allowed 
> ✖ payment: expired credit card 
> ✔ recommendation: list products
> ```

The payment service had an issue with it that I fixed in [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/197) which ill reduce to only the fix

2022-07-25 22:43 UTC, cartersocha approved these changes
LGTM

2022-07-26 05:53 UTC, julianocosta89 commented
Got the following now:
![image](https://user-images.githubusercontent.com/15364991/180933231-15403c69-51c5-4f29-a1e0-47bf4dc79e7f.png)

Are we expecting only `recommendation: list products` to be valid in this PR?
If yes, I'm good to approve.

2022-07-26 18:41 UTC, mic-max commented
> Are we expecting only `recommendation: list products` to be valid in this PR? If yes, I'm good to approve.

Correct. The payment test failures were fixed in [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/230)

2022-07-26 19:03 UTC, merged