🔭 [Frontend/ProductCatalogService] Updated Product Catalog Service Data to Match Astronomy Store
open-telemetry/opentelemetry-demo pull request #285
Opened 2022-08-10 15:44 UTC by xoscar

Fixes #.

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [X] Appropriate `CHANGELOG.md` updated for non-trivial changes

2022-08-10 16:48 UTC, reyang requested changes
Some of the images could have legal/copyright concerns, e.g. https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/e55ee5f4e734e38e5ad1a7dd6713509d70da63b9/src/frontend/public/products/LensCleaningKit.webp seems to be coming from https://www.amazon.com/Celestron-93576-Lens-Cleaning-Kit/dp/B08N5D9LXH.

2022-08-10 20:34 UTC, mic-max commented
@xoscar Could you run the local service tests to make sure nothing broke there `/test/`
Also, good idea to keep the existing `ID`
I agree with @reyang though, we should source all free to use images

2022-08-10 20:35 UTC, mic-max requested changes
@xoscar Could you run the local service tests to make sure nothing broke there `/test/`
Also, good idea to keep the existing `ID`
I agree with @reyang though, we should source all free to use images

2022-08-11 18:26 UTC, xoscar commented
Hey @mic-max  & @reyang thanks for your review. I'm getting the non-copyrighted images and I'll be updating the PR.

For the /tests/ I found out all of the tests are failing because of this change https://github.com/open-telemetry/opentelemetry-demo/commit/55d9919dde029a0d57a947cdecb157faae7844ff I think we should run the tests within the containers context so we don't have to expose the ports to localhost.

2022-08-11 20:20 UTC, mic-max commented
> context so we don't have to expose the ports to localhost
Ah yes, I forgot about that PR. I will work on getting those tests back up and running :)

2022-08-11 21:20 UTC, xoscar commented
@mic-max  & @reyang the PR should be ready for a second review 😬

2022-08-11 21:20 UTC, xoscar commented on src/adservice/src/main/java/hipstershop/AdService.java
> -    Ad hairdryer =
Updating the ads to match the new products

2022-08-15 17:49 UTC, xoscar commented
Hey @mic-max  & @reyang let me know if there is anything else I can do. The PR should be ready for its final review 😄

2022-08-17 01:35 UTC, puckpuck commented
Root spans for traces initiated from the browser are missing.
![Screen Shot 2022-08-15 at 11 38 52 PM](https://user-images.githubusercontent.com/1296118/185015110-b170b5e7-e75e-40b6-a523-acb285e06edc.png)

Using chrome dev tools, you can see 405 errors to send a payload of what seems to be an OTLP JSON payload.

![Screen Shot 2022-08-15 at 11 54 10 PM](https://user-images.githubusercontent.com/1296118/185015190-5a0eed96-0dc3-41e3-9d13-80614437a3db.png)
![Screen Shot 2022-08-15 at 11 54 39 PM](https://user-images.githubusercontent.com/1296118/185015197-36e8eac7-c27e-4324-8c12-d2ba7c00dbc2.png)

2022-08-18 00:16 UTC, mic-max approved these changes
Looks great!

2022-08-18 00:31 UTC, cartersocha commented
Could we get a changelog entry and potentially readme guidance on how to add more items? The readme update can potentially follow in another pr

2022-08-18 00:38 UTC, cartersocha commented
We should agree on some sort of file naming conventions to follow too. Our docs are word_word and pictures are word-word. These new images are WordWord.

2022-08-18 00:38 UTC, cartersocha commented
I'm fine with pictures all one way and markdown files the other but we need some sort of consistency here

2022-08-18 02:43 UTC, puckpuck approved these changes

2022-08-18 15:23 UTC, puckpuck commented
Did we address @reyang's concern about ensuring all images are not copyrighted? If so, we can resolve that conversation and merge this.

2022-08-18 15:55 UTC, xoscar commented
I just added a changelog entry and I think it should be ready to be merged. @cartersocha I'll add the steps to add a new product on a separate PR if you don't mind. CC: @puckpuck

2022-08-18 15:55 UTC, xoscar commented
@cartersocha the copyright issue has been solved as well

2022-08-19 00:11 UTC, reyang approved these changes

2022-08-19 00:32 UTC, cartersocha commented
@xoscar update & we can merge!

2022-08-19 01:50 UTC, xoscar commented
@cartersocha done 😄

2022-08-19 01:53 UTC, merged