👀 282 adding initial instrumentation setup
open-telemetry/opentelemetry-demo pull request #293
Opened 2022-08-11 17:50 UTC by xoscar

Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/283.

## Changes

Adds the instrumentation code for the front-end application. Changes include:
1. Adding auto instrumentation and propagation for the browser side.
2. Adding manual and auto instrumentation for the server (node.js) side.

2022-08-11 18:02 UTC, xoscar commented on .env
> +OTEL_EXPORTER_OTLP_TRACES_PUBLIC_ENDPOINT=http://localhost:4318/v1/traces
Adding thew OTEL public endpoint for browser connection

2022-08-11 18:03 UTC, xoscar commented on docker-compose.yml
> +      - "4318:4318"          # OTLP over HTTP receiver
Exposing the http port from the otel collector

2022-08-11 18:03 UTC, xoscar commented on src/frontend/Dockerfile
> +CMD ["sh", "-c", "npm start"]
Updating this to use a package.json script

2022-08-11 18:03 UTC, xoscar commented on src/frontend/next.config.js
> +    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
Passing the env variables to the next context

2022-08-11 18:03 UTC, xoscar commented on src/frontend/package.json
> +    "dev": "npm run grpc:generate && NODE_OPTIONS='-r ./utils/telemetry/Instrumentation.js' next dev",
requiring the Instrumentation script before running

2022-08-11 18:04 UTC, xoscar commented on src/frontend/pages/api/cart.ts
> +export default InstrumentationMiddleware(handler);
Every api route is now wrapped with this High Order Functions which provides the manual instrumentation

2022-08-11 18:04 UTC, xoscar commented on src/frontend/utils/telemetry/BackendTracer.ts
> +interface ITracer {
Provides utility functions for the instrumentation

2022-08-11 18:04 UTC, xoscar commented on src/frontend/utils/telemetry/FrontendTracer.ts
> +import { CompositePropagator, W3CBaggagePropagator, W3CTraceContextPropagator } from '@opentelemetry/core';
Creates the provider and context zones for the frontend implementation

2022-08-11 18:05 UTC, xoscar commented on src/frontend/utils/telemetry/InstrumentationMiddleware.ts
> +const InstrumentationMiddleware = (handler: NextApiHandler): NextApiHandler => {
This is the HOF that generates the manual span for each incoming request

2022-08-11 18:05 UTC, xoscar commented on src/otelcollector/otelcol-config.yml
> +          allowed_origins:
Allowing CORS for the OTEL collection for the HTTP browser side requests

2022-08-11 22:38 UTC, puckpuck requested changes

2022-08-12 14:27 UTC, xoscar commented
Hey @puckpuck thanks for the review! 😄 I just updated the PR with your comments

2022-08-15 17:47 UTC, xoscar commented
Hey @puckpuck I just updated the PR with a fix for the error you were seeing, we still need to fix the currency service issue but I think that can be done in a separate PR as the problem exists in the main branch.

The problem was that we instantiated two zone managers and Next.js already has one.

2022-08-16 03:17 UTC, puckpuck commented
@xoscar, now that we fixed the other services, can you update this branch so we have a clean setup to work from?

2022-08-16 03:19 UTC, xoscar commented
@puckpuck  done 😃

2022-08-16 22:23 UTC, mic-max approved these changes

2022-08-17 01:47 UTC, puckpuck commented
Root spans for traces initiated from the browser are missing.
![Screen Shot 2022-08-15 at 11 38 52 PM](https://user-images.githubusercontent.com/1296118/185015110-b170b5e7-e75e-40b6-a523-acb285e06edc.png)

Using chrome dev tools, you can see 405 errors to send a payload of what seems to be an OTLP JSON payload.

![Screen Shot 2022-08-15 at 11 54 10 PM](https://user-images.githubusercontent.com/1296118/185015190-5a0eed96-0dc3-41e3-9d13-80614437a3db.png)
![Screen Shot 2022-08-15 at 11 54 39 PM](https://user-images.githubusercontent.com/1296118/185015197-36e8eac7-c27e-4324-8c12-d2ba7c00dbc2.png)

2022-08-17 13:37 UTC, xoscar commented
@puckpuck the latest commit I submitted has some fixes for that problem, it should now have the correct root span starting from the client side 😄

2022-08-17 14:07 UTC, puckpuck approved these changes
Tested it end to end on my side. Works wonderfully!

2022-08-17 14:32 UTC, cartersocha commented
@xoscar update this branch & we'll merge next

2022-08-17 14:33 UTC, xoscar commented
@cartersocha Done 😉

2022-08-17 14:41 UTC, cartersocha commented
Did you implement Michael's suggestions? I'm about to resolve the conversations. 

Also please add a change log entry 😀

2022-08-17 14:51 UTC, xoscar commented
@cartersocha Yes and Done

2022-08-17 14:53 UTC, merged

2022-08-17 14:54 UTC, cartersocha commented
FYI @austinlparker you might want to pull latest for your demo