add updated versions, async call to quoteservice
open-telemetry/opentelemetry-demo pull request #370
Opened 2022-09-16 17:53 UTC by GaryPWhite

Fixes #57 .

## Changes

Added new versions for upstream dependencies, faster builds! (by a bit)

Service now utilizes `quoteservice` to fetch the quote information, sends along the price from quoteservice instead of making it up.

Notably, this is a different trace than what works for generating an ID -- because the async runtime / requests between services, this is a worthwhile difference to give examples of how `ContextGuard` does and does not work for the library. Fun stuff 😅 

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [x] Design discussion issue (N/A)

2022-09-17 07:07 UTC, cartersocha commented
Could you update our mermaid charts to reflect which service call the new quote service? The v1 architecture should have a php color and legend example + out of date service name / db

2022-09-17 07:15 UTC, cartersocha commented
the php color is already present but unused

classDef php fill:#4f5d95,color:white;

2022-09-19 07:06 UTC, julianocosta89 requested changes
@GaryPWhite thank you very much for tackling this one.
When testing the commit I saw that the span from ShippingService wasn't being linked with QuoteService.
I have added some suggestions to inject the context into the headers of the request, please feel free to modify it if you think that the way I've suggested is not the best one.

If you apply my suggestions, you may need to update the `Cargo.lock` file as well, as I've added a new dependency to manage the context propagation.

I've tested it locally and got everything stitched together 🤩

2022-09-19 07:06 UTC, julianocosta89 commented on src/shippingservice/src/shipping_service/quote.rs
> +        .await?;
```suggestion
    let req = client.request(Method::POST, quote_service_addr);

    let mut headers = HeaderMap::new();

    let cx = Context::current();
    global::get_text_map_propagator(|propagator| {
        propagator.inject_context(&cx, &mut HeaderInjector(&mut headers))
    });

    let resp = req
        .json(&reqbody)
        .headers(headers)
        .send()
        .await?
        .text_with_charset("utf-8")
        .await?;
```

2022-09-19 15:12 UTC, julianocosta89 approved these changes
Awesome! 🚀

2022-09-19 15:21 UTC, merged