[featureflag] - Move protobuf file generation to docker build
open-telemetry/opentelemetry-demo pull request #599
Opened 2022-11-19 21:22 UTC by puckpuck

## Changes

This moves the protobuf generated code files to be done in the docker build instead of a prior step. This will increase build time slightly (10-20 seconds) to set up the rebar tooling and generate the code files.

2022-11-21 16:28 UTC, austinlparker requested changes
If you're changing the build context you need to update the GHA file for build-and-release with the new context

2022-11-21 20:19 UTC, mic-max approved these changes

2022-11-22 01:54 UTC, puckpuck commented
> If you're changing the build context you need to update the GHA file for build-and-release with the new context

This is done. Also updated the `make generate-protobuf` command to generate files.

2022-11-22 14:03 UTC, austinlparker approved these changes

2022-11-22 14:03 UTC, merged