Jaeger-SPM-Config
open-telemetry/opentelemetry-demo pull request #655
Opened 2022-12-21 19:00 UTC by devrimdemiroz

# Changes

prometheus.server-url parameter and environment variable - METRICS_STORAGE_TYPE=prometheus added. So that Jaeger SPM window now shows spanmetrics.

It is not a crucial need as Jager would already be datasourced by Grafana. Nevertheless, it is nice to have.

## Merge Requirements

For new features contributions please make sure you have completed the following
essential items:

* [ ] `CHANGELOG.md` updated to document new feature additions
* [ ] Appropriate documentation updates in the [docs](../docs/) folder

Maintainers will not merge until the above have been completed. If you're unsure
which docs need to be changed ping the
[@open-telemetry/demo-approvers](https://github.com/orgs/open-telemetry/teams/demo-approvers).

2022-12-23 09:18 UTC, mviitane reviewed
Looks good and seems to work fine!
![image](https://user-images.githubusercontent.com/74129181/209308458-b888d2ce-00e6-4450-92b2-0484de90139e.png)

@devrimdemiroz, can you still fix the yamllint problem (add spaces after commas)?

2022-12-24 04:44 UTC, puckpuck requested changes

2022-12-24 04:44 UTC, puckpuck commented on docker-compose.yml
> +    command: ["--prometheus.server-url","http://${PROMETHEUS_ADDR}","--memory.max-traces", "10000", "--query.base-path", "/jaeger/ui"]
With this expanding to several parameters, let's make it a multiline array instead:

```suggestion
    command: 
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://${PROMETHEUS_ADDR}"
```

2022-12-24 18:58 UTC, devrimdemiroz reviewed
works fine. Thanks.

2022-12-24 19:16 UTC, puckpuck approved these changes

2022-12-24 19:17 UTC, puckpuck commented
Please add a changelog entry, and cleanup the failed checks.

2022-12-25 07:50 UTC, mviitane approved these changes

2022-12-25 11:55 UTC, julianocosta89 approved these changes

2022-12-25 11:55 UTC, merged

2023-01-04 17:50 UTC, puckpuck commented
So to make this change work with the Helm chart will require an update to the Jaeger helm chart to accept passing in templated variables properly.

Managing dependencies is fun 🤪