Add OTEL_RESOURCE_ATTRIBUTES to docker compose
open-telemetry/opentelemetry-demo pull request #664
Opened 2022-12-28 13:17 UTC by svrnm

# Changes

This adds OTEL_RESOURCE_ATTRIBUTES to the `.env` file and also makes use of it across all services. This allows to easily introduce `service.namespace`

## Merge Requirements

2023-01-02 08:09 UTC, julianocosta89 requested changes

2023-01-02 08:09 UTC, julianocosta89 commented on docker-compose.yml
> +      - OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES},service.name=frontend
```suggestion
      - OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES}
```

I think `service-name` was a leftover here.
We have `OTEL_SERVICE_NAME=frontend` defined below, so we are good to remove it from the `OTEL_RESOURCE_ATTRIBUTES`.

2023-01-04 05:38 UTC, puckpuck approved these changes

2023-01-04 10:52 UTC, fatsheep9146 approved these changes

2023-01-09 09:08 UTC, julianocosta89 approved these changes

2023-01-09 09:09 UTC, merged

2023-01-17 22:03 UTC, puckpuck commented
Do we want to add this to the Helm chat as well? Is this different from what we call `k8s.namespace.name` we already export as a resource attribute when deployed with Helm?