Add Sentry (sentry.io) demo to README
open-telemetry/opentelemetry-demo pull request #724
Opened 2023-01-31 14:28 UTC by AbhiPrasad

# Changes

Add Sentry's [OpenTelemetry demo](https://github.com/getsentry/opentelemetry-demo) to the vendor table.

https://github.com/getsentry/sentry/discussions/40712

![image](https://user-images.githubusercontent.com/18689448/215787605-a76fce47-a7fd-4ad7-9519-a9cfd5790469.png)

2023-01-31 19:14 UTC, puckpuck approved these changes

2023-02-01 14:50 UTC, AbhiPrasad commented
@julianocosta89 - updated for alpha order!

2023-02-01 15:52 UTC, reyang requested changes
Please maintain alphabetical order.

2023-02-01 15:53 UTC, reyang approved these changes

2023-02-01 19:57 UTC, merged