[chore] add helm chart update task to PR template
open-telemetry/opentelemetry-demo pull request #855
Opened 2023-04-27 04:36 UTC by puckpuck

Adds a task to the PR template to update the Helm chart, as well as additional comments on when docs and helm chart updates may be required.

2023-04-27 05:13 UTC, cartersocha commented
Should we link to the actual repos?

2023-04-27 05:21 UTC, julianocosta89 requested changes

2023-04-27 05:21 UTC, julianocosta89 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Appropriate documentation updates in the [docs repo]()
This change will break the link.

2023-04-27 05:23 UTC, julianocosta89 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Appropriate documentation updates in the [docs repo]()
At the bottom of the file we have the reference for the link:

`[docs]: https://opentelemetry.io/docs/demo/`

2023-04-27 05:23 UTC, julianocosta89 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] Appropriate Helm chart updates in the [helm charts repo]()
We also need to add the reference for this link.

2023-04-29 09:50 UTC, julianocosta89 approved these changes

2023-04-30 21:24 UTC, merged